-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.4
-- Fri May 18 20:57:53 2018

-- parameterized module component declaration
component ascii_table
    port (Address: in  std_logic_vector(6 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(63 downto 0));
end component;

-- parameterized module component instance
__ : ascii_table
    port map (Address(6 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(63 downto 0)=>__);
