-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.7
-- Wed Sep 26 19:57:32 2018

-- parameterized module component declaration
component sclk_pll
    port (CLKI: in  std_logic; RST: in  std_logic; 
        ENCLKOP: in  std_logic; ENCLKOS: in  std_logic; 
        CLKOP: out  std_logic; CLKOS: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : sclk_pll
    port map (CLKI=>__, RST=>__, ENCLKOP=>__, ENCLKOS=>__, CLKOP=>__, 
        CLKOS=>__, LOCK=>__);
